In [1]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive


In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/gdrive/My Drive/CICIDS2017/dataset/cicids2017_merge.csv')

In [4]:
df.shape

(2830743, 79)

In [5]:
df.columns[~(df != 0).any(axis=0)]

Index(['Bwd PSH Flags', 'Bwd URG Flags', 'Fwd Avg Bytes/Bulk',
       'Fwd Avg Packets/Bulk', 'Fwd Avg Bulk Rate', 'Bwd Avg Bytes/Bulk',
       'Bwd Avg Packets/Bulk', 'Bwd Avg Bulk Rate'],
      dtype='object')

In [6]:
df 

Destination Port  Flow Duration  ...  Idle Min   Label
0                   54865              3  ...         0  BENIGN
1                   55054            109  ...         0  BENIGN
2                   55055             52  ...         0  BENIGN
3                   46236             34  ...         0  BENIGN
4                   54863              3  ...         0  BENIGN
...                   ...            ...  ...       ...     ...
2830738                53          32215  ...         0  BENIGN
2830739                53            324  ...         0  BENIGN
2830740             58030             82  ...         0  BENIGN
2830741                53        1048635  ...         0  BENIGN
2830742                53          94939  ...         0  BENIGN

[2830743 rows x 79 columns]

remove all zero

In [7]:
df['Label'].value_counts().index

Index(['BENIGN', 'DoS Hulk', 'PortScan', 'DDoS', 'DoS GoldenEye',
       'FTP-Patator', 'SSH-Patator', 'DoS slowloris', 'DoS Slowhttptest',
       'Bot', 'Web Attack Brute Force', 'Web Attack XSS', 'Infiltration',
       'Web Attack Sql Injection', 'Heartbleed'],
      dtype='object')

In [8]:
df = df.loc[:, (df != 0).any(axis=0)]

renove nan and inf

In [9]:
df.replace([-np.inf, np.inf], np.nan, inplace=True)
df.dropna(inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4389: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  method=method,
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


select features

In [10]:
df.columns.values

array(['Destination Port', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Total Length of Fwd Packets',
       'Total Length of Bwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Fwd URG Flags',
       'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s',
       'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length',
       'Packet Length Mean', 'Packet Length Std',
       'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count',
       'RST Flag Count', 'PSH Flag 

In [11]:
#df = df[['Bwd Packet Length Max', 'Fwd Packet Length Max', 'Bwd Packet Length Std','Bwd Packet Length Min',
 #      'Label']]

In [12]:
df

Destination Port  Flow Duration  ...  Idle Min   Label
0                   54865              3  ...         0  BENIGN
1                   55054            109  ...         0  BENIGN
2                   55055             52  ...         0  BENIGN
3                   46236             34  ...         0  BENIGN
4                   54863              3  ...         0  BENIGN
...                   ...            ...  ...       ...     ...
2830738                53          32215  ...         0  BENIGN
2830739                53            324  ...         0  BENIGN
2830740             58030             82  ...         0  BENIGN
2830741                53        1048635  ...         0  BENIGN
2830742                53          94939  ...         0  BENIGN

[2827876 rows x 71 columns]

split test and train

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
seed = 1

In [15]:
train_set, test_set = train_test_split(df, test_size=0.3, random_state=seed)

split data and target

In [16]:
train_X = train_set.drop('Label', axis=1)
train_y = train_set[['Label']]
test_X = test_set.drop('Label', axis=1)
test_y = test_set[['Label']]

normalization

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
Scaler = StandardScaler()

In [19]:
train_X = Scaler.fit_transform(train_X)
test_X = Scaler.transform(test_X)

In [20]:
train_X.shape

(1979513, 70)

encode

In [21]:
from sklearn.preprocessing import OneHotEncoder

In [22]:
y_test_ada = test_y

In [23]:
En = OneHotEncoder()
train_y = En.fit_transform(train_y).toarray()
test_y = En.transform(test_y).toarray()

model

In [24]:
import sklearn.ensemble

In [25]:
model = sklearn.ensemble.RandomForestClassifier(n_estimators=50)
model.fit(train_X, train_y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=50,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [26]:
import tensorflow as tf

In [27]:
METRICS = [
      tf.keras.metrics.TruePositives(name='tp'),
      tf.keras.metrics.FalsePositives(name='fp'),
      tf.keras.metrics.TrueNegatives(name='tn'),
      tf.keras.metrics.FalseNegatives(name='fn'), 
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall'),
      #tf.keras.metrics.AUC(name='auc'),
]

metrics=METRICS

In [28]:
y_pred=model.predict(test_X)

In [29]:
def display_metrics(y_test, y_pred, label_names):
  print('\nAccuracy: {:.2f}\n'.format(accuracy_score(y_test, y_pred)))

  print('Micro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='micro')))
  print('Micro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='micro')))
  print('Micro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='micro')))

  print('Macro Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='macro')))
  print('Macro Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='macro')))
  print('Macro F1-score: {:.2f}\n'.format(f1_score(y_test, y_pred, average='macro')))

  print('Weighted Precision: {:.2f}'.format(precision_score(y_test, y_pred, average='weighted')))
  print('Weighted Recall: {:.2f}'.format(recall_score(y_test, y_pred, average='weighted')))
  print('Weighted F1-score: {:.2f}'.format(f1_score(y_test, y_pred, average='weighted')))

  print('\nClassification Report\n')
  print(classification_report(y_test, y_pred, target_names=label_names))

In [30]:
def make_value2index(attacks):
    #make dictionary
    attacks = sorted(attacks)
    d = {}
    counter=0
    for attack in attacks:
        d[attack] = counter
        counter+=1
    return d
    

In [31]:
def encode_label(Y_str):
    labels_d = make_value2index(np.unique(Y_str))
    Y = [labels_d[y_str] for y_str  in Y_str]
    Y = np.array(Y)
    return np.array(Y)

In [32]:
labels_d = make_value2index(y_test_ada['Label'])

In [33]:
np.argmax(y_pred, axis = 1)

array([0, 0, 0, ..., 0, 0, 0])

In [34]:
#importing confusion matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

from sklearn import metrics
from sklearn.metrics import accuracy_score

#importing accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import mean_squared_error,mean_absolute_error

In [35]:
from sklearn.preprocessing import OrdinalEncoder
ordinal = OrdinalEncoder()
h = ordinal.fit_transform(y_test_ada)


In [36]:
h.reshape(1,-1)[0]

array([0., 0., 0., ..., 0., 0., 0.])

In [37]:
display_metrics(h.reshape(1,-1)[0], np.argmax(y_pred, axis = 1), labels_d)


Accuracy: 1.00

Micro Precision: 1.00
Micro Recall: 1.00
Micro F1-score: 1.00

Macro Precision: 0.94
Macro Recall: 0.84
Macro F1-score: 0.86

Weighted Precision: 1.00
Weighted Recall: 1.00
Weighted F1-score: 1.00

Classification Report

                          precision    recall  f1-score   support

                  BENIGN       1.00      1.00      1.00    681389
                     Bot       0.86      0.73      0.79       582
                    DDoS       1.00      1.00      1.00     38264
           DoS GoldenEye       1.00      0.99      1.00      3134
                DoS Hulk       1.00      1.00      1.00     69288
        DoS Slowhttptest       0.99      1.00      0.99      1642
           DoS slowloris       1.00      0.99      1.00      1794
             FTP-Patator       1.00      1.00      1.00      2354
              Heartbleed       1.00      1.00      1.00         6
            Infiltration       1.00      0.70      0.82        10
                PortScan       0.99

In [38]:
!pip install lime

     |████████████████████████████████| 276kB 8.4MB/s 
  Created wheel for lime: filename=lime-0.2.0.1-cp37-none-any.whl size=283846 sha256=35e6e4a0fb51819cdd23744ee2534eb8fd223ed7f4aa2588393a2a1dc492609b
  Stored in directory: /root/.cache/pip/wheels/4c/4f/a5/0bc765457bd41378bf3ce8d17d7495369d6e7ca3b712c60c89
Successfully built lime


In [39]:
import lime.lime_tabular as a

In [40]:
class_names=df['Label'].value_counts().index
class_names

Index(['BENIGN', 'DoS Hulk', 'PortScan', 'DDoS', 'DoS GoldenEye',
       'FTP-Patator', 'SSH-Patator', 'DoS slowloris', 'DoS Slowhttptest',
       'Bot', 'Web Attack Brute Force', 'Web Attack XSS', 'Infiltration',
       'Web Attack Sql Injection', 'Heartbleed'],
      dtype='object')

In [41]:
np.array(['BENIGN', 'DoS Hulk', 'PortScan', 'DDoS', 'DoS GoldenEye',
       'FTP-Patator', 'SSH-Patator', 'DoS slowloris', 'DoS Slowhttptest',
       'Bot', 'Web Attack Brute Force', 'Web Attack XSS', 'Infiltration',
       'Web Attack Sql Injection', 'Heartbleed'])

array(['BENIGN', 'DoS Hulk', 'PortScan', 'DDoS', 'DoS GoldenEye',
       'FTP-Patator', 'SSH-Patator', 'DoS slowloris', 'DoS Slowhttptest',
       'Bot', 'Web Attack Brute Force', 'Web Attack XSS', 'Infiltration',
       'Web Attack Sql Injection', 'Heartbleed'], dtype='<U24')

In [42]:
explainer = a.LimeTabularExplainer(train_X, 
                                   feature_names=['Destination Port', 'Flow Duration', 'Total Fwd Packets',
       'Total Backward Packets', 'Total Length of Fwd Packets',
       'Total Length of Bwd Packets', 'Fwd Packet Length Max',
       'Fwd Packet Length Min', 'Fwd Packet Length Mean',
       'Fwd Packet Length Std', 'Bwd Packet Length Max',
       'Bwd Packet Length Min', 'Bwd Packet Length Mean',
       'Bwd Packet Length Std', 'Flow Bytes/s', 'Flow Packets/s',
       'Flow IAT Mean', 'Flow IAT Std', 'Flow IAT Max', 'Flow IAT Min',
       'Fwd IAT Total', 'Fwd IAT Mean', 'Fwd IAT Std', 'Fwd IAT Max',
       'Fwd IAT Min', 'Bwd IAT Total', 'Bwd IAT Mean', 'Bwd IAT Std',
       'Bwd IAT Max', 'Bwd IAT Min', 'Fwd PSH Flags', 'Fwd URG Flags',
       'Fwd Header Length', 'Bwd Header Length', 'Fwd Packets/s',
       'Bwd Packets/s', 'Min Packet Length', 'Max Packet Length',
       'Packet Length Mean', 'Packet Length Std',
       'Packet Length Variance', 'FIN Flag Count', 'SYN Flag Count',
       'RST Flag Count', 'PSH Flag Count', 'ACK Flag Count',
       'URG Flag Count', 'CWE Flag Count', 'ECE Flag Count',
       'Down/Up Ratio', 'Average Packet Size', 'Avg Fwd Segment Size',
       'Avg Bwd Segment Size', 'Fwd Header Length.1',
       'Subflow Fwd Packets', 'Subflow Fwd Bytes', 'Subflow Bwd Packets',
       'Subflow Bwd Bytes', 'Init_Win_bytes_forward',
       'Init_Win_bytes_backward', 'act_data_pkt_fwd',
       'min_seg_size_forward', 'Active Mean', 'Active Std', 'Active Max',
       'Active Min', 'Idle Mean', 'Idle Std', 'Idle Max', 'Idle Min'], 
                                   class_names=np.array(['BENIGN', 'DoS Hulk', 'PortScan', 'DDoS', 'DoS GoldenEye',
       'FTP-Patator', 'SSH-Patator', 'DoS slowloris', 'DoS Slowhttptest',
       'Bot', 'Web Attack Brute Force', 'Web Attack XSS', 'Infiltration',
       'Web Attack Sql Injection', 'Heartbleed']),
                                   discretize_continuous=True)

In [48]:
i = np.random.randint(0, test_X.shape[0])
exp = explainer.explain_instance(test_X[i], model.predict_proba, num_features=70, top_labels=1)

AttributeError: ignored

In [47]:
test_X[i]

array([-4.38318925e-01, -4.37452779e-01, -7.15582624e-03, -8.42225911e-03,
       -3.31398863e-02, -6.98942336e-03, -2.25594762e-01,  4.49287516e-01,
       -6.59955889e-02, -2.44935497e-01, -3.70710413e-01,  1.57991180e+00,
       -2.57916455e-01, -3.99709927e-01, -5.73382730e-02, -2.77938307e-01,
       -2.84846821e-01, -3.59605794e-01, -3.73000114e-01, -5.48653626e-02,
       -4.29730233e-01, -2.71849801e-01, -3.35434011e-01, -3.66241041e-01,
       -1.18684823e-01, -3.44606296e-01, -2.03301119e-01, -2.36855275e-01,
       -2.73148254e-01, -1.16259271e-01, -2.20120645e-01, -1.06619530e-02,
        1.26452929e-03,  1.68205793e-03, -2.57680356e-01, -1.82648084e-01,
        1.16992525e+00, -3.95055410e-01, -3.15358779e-01, -3.86941424e-01,
       -2.93807895e-01, -1.91387686e-01, -2.20120645e-01, -1.54434243e-02,
       -6.52060233e-01, -6.78637752e-01, -3.23872806e-01, -1.06619530e-02,
       -1.54597791e-02, -1.00818638e+00, -3.12681763e-01, -6.59955889e-02,
       -2.57916455e-01,  

In [ ]:
test_X[i].shape

In [ ]:
train_X.shape